# Generated by Django 5.1.5 on 2025-08-13 06:19

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('jwt_token', models.CharField(blank=True, max_length=500, null=True)),
                ('is_main_user', models.BooleanField(default=False)),
                ('is_sub_mainuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('parent_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MyKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membershipno', models.IntegerField(blank=True, null=True)),
                ('membershiptype', models.CharField(blank=True, choices=[('senior', 'Senior'), ('junior', 'Junior')], max_length=10)),
                ('depositorsname', models.CharField(blank=True, max_length=100)),
                ('depositorsaddress', models.TextField(blank=True)),
                ('nameofthecompany', models.CharField(blank=True, max_length=100)),
                ('customeridno', models.IntegerField(blank=True, null=True)),
                ('receiptno', models.IntegerField(blank=True, null=True)),
                ('modno', models.IntegerField(blank=True, null=True)),
                ('depositamount', models.IntegerField(blank=True, null=True)),
                ('intrefundamount', models.IntegerField(blank=True, null=True)),
                ('defaultamount', models.IntegerField(blank=True, null=True)),
                ('investmentdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('bondholdername', models.CharField(blank=True, max_length=100)),
                ('projectname', models.CharField(blank=True, max_length=100)),
                ('depositormobile_number', models.CharField(blank=True, max_length=12)),
                ('agentname', models.CharField(blank=True, max_length=100)),
                ('agentaddress', models.TextField(blank=True)),
                ('bondimage', models.ImageField(blank=True, null=True, upload_to='kyc_uploads/')),
                ('bondimagetype', models.CharField(blank=True, choices=[('original', 'Original'), ('xerox', 'Xerox')], max_length=10, null=True)),
                ('nameofdirector', models.CharField(blank=True, max_length=100)),
                ('aadhar_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('ration_number', models.CharField(blank=True, max_length=20)),
                ('bankname', models.CharField(blank=True, max_length=100)),
                ('bankaccno', models.CharField(blank=True, max_length=20)),
                ('ifscno', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_my_kycs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_kycs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('fathername', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=20)),
                ('aadhar_front_image', models.ImageField(blank=True, null=True, upload_to='sub_aadhar_front/')),
                ('aadhar_back_image', models.ImageField(blank=True, null=True, upload_to='sub_aadhar_back/')),
                ('profession', models.CharField(max_length=100)),
                ('contactSH', models.CharField(max_length=100)),
                ('nameSH', models.CharField(max_length=100)),
                ('investmentamt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('passportphoto', models.ImageField(blank=True, null=True, upload_to='sub_passport_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_kycs_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sub_kycs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BondImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bonds/')),
                ('companyname', models.CharField(max_length=100)),
                ('projectname', models.CharField(max_length=100)),
                ('investment_date', models.DateField(default=datetime.date.today)),
                ('customer_id', models.CharField(max_length=10)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('my_kyc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='app.mykyc')),
                ('sub_kyc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonds', to='app.subkyc')),
            ],
        ),
    ]
