# Generated by Django 5.1.5 on 2025-08-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mykyc',
            name='agentaddress',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='agentname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='bankaccno',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='bankname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='bondholdername',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='depositormobile_number',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='depositorsaddress',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='depositorsname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='ifscno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='membershipno',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='nameofdirector',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='nameofthecompany',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='projectname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
