# Generated by Django 5.1.5 on 2025-08-13 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='bondimagetype',
        ),
    ]
