# Generated by Django 5.1.5 on 2025-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_mykyc_bondimagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mykyc',
            name='bondimagetype',
            field=models.CharField(blank=True, choices=[('original', 'Original'), ('xerox', 'Xerox')], max_length=10, null=True),
        ),
    ]
