# Generated by Django 5.1.5 on 2025-08-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mykyc_bondimagetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='bondholdername',
        ),
        migrations.AddField(
            model_name='bondimage',
            name='bondholdername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
