# Generated by Django 5.1.5 on 2025-09-01 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_mykyc_bondholdername_bondimage_bondholdername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='bondimage',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='bondimagetype',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='customeridno',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='defaultamount',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='depositamount',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='intrefundamount',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='investmentdate',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='modno',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='nameofthecompany',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='receiptno',
        ),
        migrations.AddField(
            model_name='mykyc',
            name='aadhar_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhar/'),
        ),
        migrations.AddField(
            model_name='mykyc',
            name='aadhar_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/aadhar/'),
        ),
        migrations.AddField(
            model_name='mykyc',
            name='bondholdername',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mykyc',
            name='passportphoto',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/passport/'),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_my_kycs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='depositormobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_kycs', to=settings.AUTH_USER_MODEL),
        ),
    ]
