# Generated by Django 5.1.5 on 2025-09-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_mykyc_bondimage_remove_mykyc_bondimagetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='aadhar_back_image',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='aadhar_front_image',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='passportphoto',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='projectname',
        ),
        migrations.AlterField(
            model_name='mykyc',
            name='membershiptype',
            field=models.CharField(blank=True, choices=[('senior', 'Senior Citizen'), ('junior', 'Junior Citizen')], max_length=10),
        ),
    ]
