# Generated by Django 5.1.5 on 2025-09-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_bondimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mykyc',
            name='membershiptype',
            field=models.CharField(blank=True, choices=[('senior', 'Senior Citizen'), ('junior', 'Junior Citizen')], max_length=50),
        ),
    ]
