# Generated by Django 5.1.5 on 2025-09-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_mykyc_depositorsmailid_alter_mykyc_associationname'),
    ]

    operations = [
        migrations.AddField(
            model_name='mykyc',
            name='agentmobnum',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
