# Generated by Django 5.1.5 on 2025-09-13 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_mykyc_agentmobnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bondimage',
            name='balanceamount',
        ),
        migrations.RemoveField(
            model_name='bondimage',
            name='refundamount',
        ),
    ]
