# Generated by Django 5.1.5 on 2025-09-13 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_bondimage_balanceamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondimage',
            name='dateofresale',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bondimage',
            name='tokennum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
