# Generated by Django 5.1.5 on 2025-09-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_bondimage_dateofresale_bondimage_tokennum'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondimage',
            name='bondimagetype',
            field=models.CharField(blank=True, choices=[('original', 'Original'), ('xerox', 'Xerox')], max_length=50, null=True),
        ),
    ]
