# Generated by Django 5.1.5 on 2025-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_bondimage_bondimagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mykyc',
            name='agentmailid',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
