# Generated by Django 5.1.5 on 2025-09-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_mykyc_agentmailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondimage',
            name='remarks',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
