# Generated by Django 5.1.5 on 2025-09-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_bondimage_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondimage',
            name='agentid',
            field=models.IntegerField(blank=True, default=0, max_length=10),
        ),
    ]
