# Generated by Django 5.1.5 on 2025-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_bondimage_agentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondimage',
            name='agentid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
