# Generated by Django 5.1.5 on 2025-09-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_bondimage_agentid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='membershiptype',
        ),
    ]
