# Generated by Django 5.1.5 on 2025-09-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_mykyc_membershiptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mykyc',
            name='associationname',
            field=models.CharField(blank=True, choices=[('SENIOR', 'SENIOR'), ('JUNIOR', 'JUNIOR')], max_length=255),
        ),
    ]
