# Generated by Django 5.1.5 on 2025-09-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_mykyc_associationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mykyc',
            name='associationname',
            field=models.CharField(blank=True, choices=[('NEOMAX JUNIOR CITIZEN INVESTORS WELFARE ASSOCIATION - TRICHY', 'NEOMAX JUNIOR CITIZEN INVESTORS WELFARE ASSOCIATION - TRICHY'), ('NEOMAX JUNIOR CITIZEN INVESTORS WELFARE ASSOCIATION - TRICHY', 'NEOMAX JUNIOR CITIZEN INVESTORS WELFARE ASSOCIATION - TRICHY')], max_length=255),
        ),
    ]
