# Generated by Django 5.1.5 on 2025-10-13 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_mykyc_associationname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mykyc',
            name='agentaddress',
        ),
        migrations.RemoveField(
            model_name='mykyc',
            name='agentmailid',
        ),
    ]
